apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: finisher
  name: finisher
spec:
  replicas: 1
  selector:
    matchLabels:
      name: finisher
  template:
    spec:
      containers:
      - command:
        - /bin/call
        image: dummy:dummy
        imagePullPolicy: IfNotPresent
        name: finisher
        ports:
        - containerPort: 8000
          name: http
        resources:
          limits:
            cpu: "0.4"
            memory: 512Mi
          requests:
            cpu: "0.05"
            memory: 256Mi